name: lanjian

services:
  adminer:
    image: adminer:latest
    restart: unless-stopped
    profiles:
      - tools
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lanjian-network

networks:
  lanjian-network:
    name: lanjian-network
    driver: bridge
